force-app/main/default/objects/Expense_Report__c/Expense_Report__c.object-meta.xml
<CustomObject>
    <label>Expense Report</label>
    <nameField>
        <label>Expense Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Report__c/fields/Active_for_App__c.field-meta.xml
<CustomField>
    <fullName>Active_for_App__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active for App</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExpenseReportServices.cls
public with sharing class ExpenseReportServices {

  // Need to bulkify
  public static void activateExpenseReport(List<Expense_Report__c> triggerNew) {
    // Determine if any new record has set make active set to true
    Expense_Report__c newActiveRecord;

    for (Expense_Report__c expenseReport : triggerNew) {
      if (expenseReport.Active_for_App__c == true) {
        newActiveRecord = expenseReport;
        break;
      }
    }

    // Exit if new records are not requesting to be active
    if (newActiveRecord == null) {
      return;
    }

    // Deactivate any other expense reports if any are active
    List<Expense_Report__c> previousActive = [
      SELECT Id
      FROM Expense_Report__c
      WHERE Active_for_App__c = true
      AND Id <>: newActiveRecord.Id
   ];

   System.debug(JSON.serialize(previousActive));

    for (Expense_Report__c expenseReport : previousActive) {
      expenseReport.Active_for_App__c = false;
    }

    // Update previous active to inactive if any exist
    if (!previousActive.isEmpty()) {
      update previousActive;
    }

  }

}